AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  hyeapp - FastAPI Application Deployed via AWS SAM on Lambda and API Gateway

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: fastapiService
        POWERTOOLS_LOG_LEVEL: INFO
        TRACING: Active

Resources:
  FastAPIAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hyeapp/
      Handler: main.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SubnetIds:
          - subnet-047eacb30af5a54e9
          - subnet-067a9812a90e9dcd9
          - subnet-082ac0ee03d7ad206
        SecurityGroupIds:
          - sg-04d1c3b8efb98728d
          - sg-09ccc352929cc46b0
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+} # Catch-all proxy path for all endpoints in the FastAPI app
            Method: ANY
            RestApiId: !Ref FastAPIRestApi
      Environment:
        Variables:
          HYE_DB_USERNAME: "postgres"
          HYE_DB_PASSWORD: "MaxOutPostAnalysis99"
          HYE_DB_NAME: "hye"
          HYE_DB_HOST: "hye.cd11c6bnabfd.us-east-2.rds.amazonaws.com"
          HYE_DB_PORT: 5432
          COGNITO_USER_POOL_ID: "us-east-2_j7TTNd6qj"
          REGION: "us-east-2"
          COGNITO_APP_CLIENT_ID: "37687bqb1t1t0osibaovkhctp2"
  FastAPIRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  FastAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for the FastAPI app"
    Value: !Sub "https://${FastAPIRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FastAPIAppFunctionArn:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIAppFunction.Arn
  FastAPIAppFunctionIamRole:
    Description: "IAM Role ARN for the FastAPI Lambda function"
    Value: !GetAtt FastAPIAppFunctionRole.Arn
